---
title: Company Site
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
url: https://www.skillbill.it
theme: minima
pagination:
  enabled: true
  collection: 'posts'
  per_page: 3
  permalink: '/page/:num/'
  category: 'posts'
  tag: ''
  trail:
    before: 2
    after: 2
plugins:
- jekyll-feed
- jekyll-paginate-v2
show_drafts: true
