---
title: Company Site
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
baseurl: ''
url: https://www.skillbill.it
theme: minima
plugins:
- jekyll-feed
