---
title: Company Site
timezone: Europe/Rome
collections:
  customers:
    title: Customers
    output: true
  posts:
    title: Posts
    output: true
  products:
    title: Products
    output: true
  uploads:
    title: Uploads
    output: true
url: https://www.skillbill.it
future: true
theme: minima
pagination:
  enabled: true
  collection: posts
  per_page: 10
  permalink: "/page/:num/"
  category: posts
  sort_reverse: true
  trail:
    before: 2
    after: 2
autopages:
  enabled: true
  categories:
    layouts:
    - autopage_categories.html
  tags:
    layouts:
    - autopage_tags.html
    title: Posts tagged with :tag
    permalink: "/tag/:tag"
    slugify:
      mode: default
      case: true
plugins:
- jekyll-feed
- jekyll-paginate-v2
- rouge
show_drafts: true
highlighter: rouge
