# config.yml

backend:
  name: github
  repo: Skillbill/company-site
media_folder: 'images'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - { name: Ciccio }