# config.yml

backend:
  name: github
  repo: Skillbill/company-site
  api_root: https://api.github.com
  site_domain: location.hostname
  base_url: https://api.netlify.com
  auth_endpoint: auth
media_folder: 'images'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - { name: Ciccio }
